@URL = http://localhost:5284

###
GET {{URL}}/users
Accept: application/json

### 
GET {{URL}}/users/1
Accept: application/json

### 
POST {{URL}}/users
Content-Type: application/json

{
  "fullName": "Katya",
  "email": "katya@yandex.com",
  "password": "1",
  "Specialization": "katyas", 
  "location": "USA",
  "bio": "asdasdasfsdfsfsdfdf"
}
###
POST {{URL}}/users/admin
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "secure123",
    "fullName": "Admin"
}
###
POST {{URL}}/users/reviewer
Content-Type: application/json

{
    "email": "andrey.terent1ev@mail.ru",
    "password": "123456",
    "fullName": "Reviewer Boba"
}
###
PATCH {{URL}}/users/1
Content-Type: application/json

{
  "fullName": "Andrey",
  "email": "andrey@yandex.com",
  "password": "1",
  "Specialization": "andreys", 
  "location": "USA",
  "bio": "asdasdasfsdfsfsdfdf"
}

### 
DELETE {{URL}}/users/6