@URL = http://localhost:5284

###
GET {{URL}}/users
Accept: application/json

### 
GET {{URL}}/users/1
Accept: application/json

### 
POST {{URL}}/users
Content-Type: application/json

{
  "fullName": "Katya",
  "email": "katya@yandex.com",
  "password": "1",
  "Specialization": "katyas", 
  "location": "USA",
  "bio": "asdasdasfsdfsfsdfdf"
}
###
PATCH {{URL}}/users/1
Content-Type: application/json

{
  "fullName": "Andrey",
  "email": "andrey@yandex.com",
  "password": "1",
  "Specialization": "andreys", 
  "location": "USA",
  "bio": "asdasdasfsdfsfsdfdf"
}

### 
DELETE {{URL}}/users/1