@URL = http://localhost:5284

###
GET {{URL}}/users
Accept: application/json

### 
GET {{URL}}/users/1
Accept: application/json

### 
POST {{URL}}/users
Content-Type: application/json

{
  "fullName": "Katya",
  "email": "katya@yandex.com",
  "password": "1",
  "Specialization": "katyas", 
  "location": "USA",
  "bio": "asdasdasfsdfsfsdfdf"
}
###
POST {{URL}}/users/admin
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "secure123",
    "fullName": "Admin"
}
###
POST {{URL}}/users/reviewer
Content-Type: application/json

{
    "email": "andrey.terent1ev@mail.ru",
    "password": "123456",
    "fullName": "Boba"
}
###
PATCH {{URL}}/users/1
Content-Type: application/json

{
  "fullName": "Andrey",
  "email": "andrey@yandex.com",
  "password": "1",
  "Specialization": "andreys", 
  "location": "USA",
  "bio": "asdasdasfsdfsfsdfdf"
}

###
POST {{URL}}/users/1/upload-resume
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="1.pdf"
Content-Type: application/pdf

< ./1.pdf
--WebAppBoundary--

###
POST {{URL}}/users/2/upload-resume
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2.docx"
Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document

< ./2.docx
--WebAppBoundary--

###
GET {{URL}}/users/1/download-resume
Accept: application/pdf

###
PATCH {{URL}}/users/2/update-resume
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="3.docx"
Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document

< ./3.docx
--WebAppBoundary--

###
POST {{URL}}/users/1/upload-resume
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="pic.png"
Content-Type: image/png

< ./pic.png
--WebAppBoundary--

###
PATCH {{URL}}/users/1/update-resume
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="pic.png"
Content-Type: image/png

< ./pic.png
--WebAppBoundary--


### 
DELETE {{URL}}/users/1